name: Deploy
on: 
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker login
      uses: docker/login-action@master
      with:
        username: ${{ secrets.REGISRTY_USER }}
        password: ${{ secrets.REGISRTY_PASSWORD }} 
      
    - name: Docker build
      run: docker build . -t ${{ secrets.REGISRTY_USER }}/${{ github.event.repository.name }}
      
    - name: Docker push
      run: docker push ${{ secrets.REGISRTY_USER }}/${{ github.event.repository.name }}
      
    - name: Replace deployed
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DOMAIN }}
        port: ${{ secrets.HOST_PORT }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd /${{ github.event.repository.name }}
          docker-compose down
          docker rmi ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}
          docker-compose up --detach
